/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pruebas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import smileManager.Controlador.Conexion;

/**
 *
 * @author Ferna
 */
public class Insercion extends javax.swing.JFrame {
    
    Conexion conexion = new Conexion();
    Connection connection;
    ArrayList<String> nombre = new ArrayList<>();
    ArrayList<String> domicilio = new ArrayList<>();
    ArrayList<String> DOB = new ArrayList<>();
    ArrayList<String> tel = new ArrayList<>();
    

    /**
     * Creates new form Insercion
     */
    public Insercion() {
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txt.setColumns(20);
        txt.setRows(5);
        jScrollPane1.setViewportView(txt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void mostrar(){

        int contRead = 0, contWrite = 0;
        try {
            connection = conexion.conectarDB();
            ResultSet result;
            PreparedStatement statement = connection.prepareStatement("select * from Pacientes");
            statement.execute();
            result = statement.executeQuery();
            while (result.next()) {
                
                nombre.add(result.getString("Nombre"));
                txt.append("Nombre: "+result.getString("Nombre"));
                
                domicilio.add(result.getString("Domicilio"));
                txt.append(" Domicilio: "+result.getString("Domicilio"));
                
                DOB.add(result.getString("DOB"));
                txt.append(" Fecha de Nacimiento: "+result.getString("DOB"));
                
                tel.add(result.getString("Telefono"));
                txt.append(" Telefono: "+result.getString("Telefono")+"\n");
                
                contRead++;
            }
            JOptionPane.showMessageDialog(null, "Se insertaron "+contRead+" registros ","Reporte de Insercion",JOptionPane.OK_OPTION);
            
            for (int i = 0; i < contRead; i++) {
                statement = connection.prepareStatement("insert into Pacientes(Nombre,Domicilio,DOB,Telefono ) values('" + nombre.get(i) + "','" + domicilio.get(i) + "','" + DOB.get(i) + "','" + tel.get(i) + "')");
                statement.execute();
            }

        } catch (SQLException e) {
            System.err.println(e);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insercion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insercion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insercion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insercion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insercion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
